import type {
  AnalyticsData,
  AuditEvent,
  Customer,
  Merchant,
  Policy,
  RecoveryCase,
  RecoveryDecision,
  Transaction,
} from "@/lib/mock-data/types";

export const merchant: Merchant = {
  id: "m-1001",
  name: "Aarav Mehta",
  storeName: "Northwind Studio",
  email: "aarav@northwindstudio.in",
  status: "Test Mode",
  region: "India / IN",
  accountTier: "Growth Merchant",
};

export const customers: Customer[] = [
  {
    id: "c-1001",
    name: "Customer A",
    email: "customerA@example.com",
    totalOrders: 14,
    lifetimeValue: 64320,
    paymentHistory: ["Success", "Success", "Failed", "Success", "Success"],
  },
  {
    id: "c-1002",
    name: "Customer B",
    email: "customerB@example.com",
    totalOrders: 9,
    lifetimeValue: 48120,
    paymentHistory: ["Success", "Success", "Failed", "Success", "Failed"],
  },
  {
    id: "c-1003",
    name: "Customer C",
    email: "customerC@example.com",
    totalOrders: 22,
    lifetimeValue: 114200,
    paymentHistory: ["Success", "Success", "Success", "Success", "Failed"],
  },
  {
    id: "c-1004",
    name: "Priya Shah",
    email: "priya@example.com",
    totalOrders: 17,
    lifetimeValue: 87900,
    paymentHistory: ["Failed", "Success", "Success", "Success", "Success"],
  },
  {
    id: "c-1005",
    name: "Nikhil Rao",
    email: "nikhil@example.com",
    totalOrders: 12,
    lifetimeValue: 58110,
    paymentHistory: ["Success", "Success", "Failed", "Success", "Failed"],
  },
];

export const transactions: Transaction[] = [
  {
    id: "TXN_10291",
    customerId: "c-1001",
    customerName: "Customer A",
    amount: 4999,
    currency: "INR",
    paymentMethod: "UPI",
    status: "Recovered",
    failureReason: "Temporary payment failure",
    recoveryStatus: "Recovered",
    createdAt: "2026-08-18T10:32:00Z",
    updatedAt: "2026-08-18T10:38:00Z",
    riskLevel: "High",
    recoveryProbability: 84,
    recommendedAction: "Retry payment",
    policyResult: "Approved",
    expectedRecoveryValue: 4200,
    isRecoverable: true,
  },
  {
    id: "TXN_10305",
    customerId: "c-1002",
    customerName: "Customer B",
    amount: 12800,
    currency: "INR",
    paymentMethod: "Card",
    status: "Failed",
    failureReason: "Authentication failure",
    recoveryStatus: "Recommended",
    createdAt: "2026-08-20T12:42:00Z",
    updatedAt: "2026-08-20T12:52:00Z",
    riskLevel: "High",
    recoveryProbability: 71,
    recommendedAction: "Send recovery link",
    policyResult: "Approved",
    expectedRecoveryValue: 9500,
    isRecoverable: true,
  },
  {
    id: "TXN_10322",
    customerId: "c-1003",
    customerName: "Customer C",
    amount: 8600,
    currency: "INR",
    paymentMethod: "Net Banking",
    status: "Abandoned",
    failureReason: "Abandoned checkout",
    recoveryStatus: "Awaiting approval",
    createdAt: "2026-08-20T17:18:00Z",
    updatedAt: "2026-08-20T17:44:00Z",
    riskLevel: "Medium",
    recoveryProbability: 63,
    recommendedAction: "Offer alternative payment",
    policyResult: "Needs review",
    expectedRecoveryValue: 6200,
    isRecoverable: true,
  },
  {
    id: "TXN_10341",
    customerId: "c-1004",
    customerName: "Priya Shah",
    amount: 22400,
    currency: "INR",
    paymentMethod: "Wallet",
    status: "Failed",
    failureReason: "Payment method issue",
    recoveryStatus: "Pending",
    createdAt: "2026-08-19T08:11:00Z",
    updatedAt: "2026-08-19T08:30:00Z",
    riskLevel: "High",
    recoveryProbability: 78,
    recommendedAction: "Retry payment",
    policyResult: "Blocked",
    expectedRecoveryValue: 18400,
    isRecoverable: true,
  },
  {
    id: "TXN_10387",
    customerId: "c-1005",
    customerName: "Nikhil Rao",
    amount: 6700,
    currency: "INR",
    paymentMethod: "EMI",
    status: "Recovery attempted",
    failureReason: "Temporary payment failure",
    recoveryStatus: "Recovered",
    createdAt: "2026-08-17T15:06:00Z",
    updatedAt: "2026-08-17T15:25:00Z",
    riskLevel: "Medium",
    recoveryProbability: 66,
    recommendedAction: "Customer notification",
    policyResult: "Approved",
    expectedRecoveryValue: 5100,
    isRecoverable: true,
  },
  {
    id: "TXN_10402",
    customerId: "c-1002",
    customerName: "Customer B",
    amount: 12990,
    currency: "INR",
    paymentMethod: "Card",
    status: "Failed",
    failureReason: "Temporary payment failure",
    recoveryStatus: "None",
    createdAt: "2026-08-20T20:18:00Z",
    updatedAt: "2026-08-20T20:18:00Z",
    riskLevel: "Medium",
    recoveryProbability: 54,
    recommendedAction: "Retry payment",
    policyResult: "Approved",
    expectedRecoveryValue: 9200,
    isRecoverable: true,
  },
];

export const recoveryCases: RecoveryCase[] = [
  {
    id: "rc-1",
    transactionId: "TXN_10305",
    customerName: "Customer B",
    amount: 12800,
    recoveryProbability: 71,
    recommendedAction: "Send recovery link",
    reason:
      "Temporary failure with strong customer payment history and no previous recovery attempt.",
    expectedRecoveryValue: 9500,
    policyResult: "Approved",
    status: "Recommended",
    lastUpdated: "2 hours ago",
  },
  {
    id: "rc-2",
    transactionId: "TXN_10322",
    customerName: "Customer C",
    amount: 8600,
    recoveryProbability: 63,
    recommendedAction: "Offer alternative payment",
    reason: "Checkout was abandoned after a payment-method validation error.",
    expectedRecoveryValue: 6200,
    policyResult: "Needs review",
    status: "Awaiting approval",
    lastUpdated: "45 minutes ago",
  },
  {
    id: "rc-3",
    transactionId: "TXN_10291",
    customerName: "Customer A",
    amount: 4999,
    recoveryProbability: 84,
    recommendedAction: "Retry payment",
    reason: "Strong customer lifetime value and a temporary failure pattern.",
    expectedRecoveryValue: 4200,
    policyResult: "Approved",
    status: "Completed",
    lastUpdated: "Today",
  },
];

export const recoveryDecisionDetails: RecoveryDecision[] = [
  {
    id: "rd-10291",
    transactionId: "TXN_10291",
    recoveryProbability: 84,
    recommendedAction: "RETRY_PAYMENT",
    reason: "Temporary failure with strong customer payment history and no prior recovery attempt.",
    reasoningSignals: [
      "6 previous successful payments",
      "Temporary failure reason",
      "High customer lifetime value",
      "No previous recovery attempt",
    ],
    riskFactors: ["Current payment failure"],
    policyChecks: [
      { label: "Retry limit", value: "1 / 2", result: "Pass" },
      { label: "Recovery window", value: "Within allowed window", result: "Pass" },
      { label: "Customer message cap", value: "0 / 2", result: "Pass" },
    ],
    expectedRecoveryValue: 4200,
    status: "Executed",
  },
];

export const policy: Policy = {
  id: "pol-001",
  maximumRetryAttempts: 2,
  maximumCustomerMessages: 2,
  maximumDiscount: 200,
  recoveryWindowHours: 48,
  maximumAutoRecoveryAmount: 25000,
  requireApprovalAbove: 25000,
  mode: "Assisted",
};

export const auditEvents: AuditEvent[] = [
  {
    id: "evt-1",
    timestamp: "2026-08-18T10:35:02Z",
    transactionId: "TXN_10291",
    event: "AI_DECISION",
    actor: "Recovery Agent",
    aiDecision: "RETRY_PAYMENT",
    policyResult: "Approved",
    action: "Pending",
    outcome: "Pending",
  },
  {
    id: "evt-2",
    timestamp: "2026-08-18T10:37:41Z",
    transactionId: "TXN_10291",
    event: "RECOVERY_EXECUTED",
    actor: "System",
    aiDecision: "RETRY_PAYMENT",
    policyResult: "Approved",
    action: "Retry",
    outcome: "Success",
  },
  {
    id: "evt-3",
    timestamp: "2026-08-20T12:48:14Z",
    transactionId: "TXN_10305",
    event: "AI_DECISION",
    actor: "Recovery Agent",
    aiDecision: "SEND_LINK",
    policyResult: "Approved",
    action: "Pending",
    outcome: "Pending",
  },
  {
    id: "evt-4",
    timestamp: "2026-08-20T17:35:08Z",
    transactionId: "TXN_10322",
    event: "POLICY_REVIEW",
    actor: "Ops Team",
    aiDecision: "ALTERNATIVE_PAYMENT",
    policyResult: "Pending",
    action: "Awaiting approval",
    outcome: "Pending",
  },
];

export const analyticsData: AnalyticsData = {
  kpis: [
    {
      label: "Revenue at Risk",
      value: "₹18.4L",
      delta: "+8.2% vs previous 30 days",
      description: "Total value with failure and abandonment exposure",
    },
    {
      label: "Potentially Recoverable",
      value: "₹11.2L",
      delta: "+12.7% vs previous 30 days",
      description: "Transactions with recovery probability above threshold",
    },
    {
      label: "Revenue Recovered",
      value: "₹6.72L",
      delta: "+18.4% vs previous 30 days",
      description: "Monetized recovery generated across recent attempts",
    },
    {
      label: "Recovery Rate",
      value: "59.8%",
      delta: "+6.1 pts vs previous 30 days",
      description: "Share of recoverable risk converted into recovered revenue",
    },
  ],
  revenueTrend: [
    { label: "Jan", revenueAtRisk: 98000, recovered: 43000 },
    { label: "Feb", revenueAtRisk: 110000, recovered: 49000 },
    { label: "Mar", revenueAtRisk: 142000, recovered: 61000 },
    { label: "Apr", revenueAtRisk: 160000, recovered: 69000 },
    { label: "May", revenueAtRisk: 170000, recovered: 81000 },
    { label: "Jun", revenueAtRisk: 184000, recovered: 92000 },
  ],
  funnel: [
    { label: "Failed / abandoned revenue", value: 184000 },
    { label: "Potentially recoverable", value: 112000 },
    { label: "Recovery attempts", value: 81000 },
    { label: "Successfully recovered", value: 67200 },
  ],
  recoveryReasons: [
    { name: "Temporary payment failure", value: 38 },
    { name: "Abandoned checkout", value: 27 },
    { name: "Authentication failure", value: 18 },
    { name: "Payment method issue", value: 12 },
    { name: "Other", value: 5 },
  ],
  recoveryStrategies: [
    { strategy: "Retry", value: 42 },
    { strategy: "Recovery Link", value: 28 },
    { strategy: "Customer Notification", value: 17 },
    { strategy: "Alternative Payment", value: 9 },
    { strategy: "Incentive", value: 4 },
  ],
  outcomes: [
    { name: "Recovered", value: 59 },
    { name: "Pending", value: 21 },
    { name: "Blocked", value: 13 },
    { name: "Failed", value: 7 },
  ],
  failureReasons: [
    { name: "Temporary failure", value: 46 },
    { name: "Network timeout", value: 21 },
    { name: "Authentication", value: 17 },
    { name: "Method issue", value: 10 },
    { name: "Cart abandonment", value: 6 },
  ],
  paymentMethods: [
    { name: "UPI", value: 32 },
    { name: "Card", value: 28 },
    { name: "Net Banking", value: 18 },
    { name: "Wallet", value: 12 },
    { name: "EMI", value: 10 },
  ],
  experiments: {
    transactionsTested: 5000,
    baselineRecovered: 182000,
    aiRecovered: 321000,
    improvement: 76.4,
    restorationRate: 64.2,
    unnecessaryIntervention: 11.7,
    averageRecoveryCost: 386,
  },
};
